# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])

PublicBodyCategories.add(:hu, [
    "Igazságszolgáltatás",
        [ "bíróság","bíróság","bíróság"],
        [ "bírósági_hivatal","bírósági hivatal","bírósági hivatal"],
        [ "bírói_tanács","bírói tanács","bírói tanács"],
	      [ "cégbíróság","cégbíróság","cégbíróság"],   
        [ "független_közjogi_szerv","független közjogi szerv","független közjogi szerv"],
        [ "ítélőtábla","ítélőtábla","ítélőtábla"],
        [ "munkaügyi_bíróság","munkaügyi bíróság","munkaügyi bíróság"],
        [ "törvényszék","törvényszék","törvényszék"],
        [ "ügyészség","ügyészség","ügyészség"],
    "Közigazgatás",
        [ "egyéb_közfeladatot_ellátó_szervek","egyéb közfeladatot ellátó szervek","mely egy egyéb közfeladatot ellátó szerv"],
        [ "felügyelet","felügyelet","felügyelet"],
        [ "hatóság","hatóság"],
        [ "hivatal","hivatal","hivatal"],
        [ "helyi_közigazgatás","helyi közigazgatás","helyi közigazgatás"],
        [ "központi_közigazgatás","központi közigazgatás","központi közigazgatás"],
        [ "minisztérium","minisztérium","minisztérium"],
        [ "önkormányzat","önkormányzat","önkormányzat"],
        [ "polgármesteri_hivatal","polgármesteri hivatal","polgármesteri hivatal"],
     "Intézménytípusok",
        [ "akadémia","akadémia","akadémia"],
        [ "állami_tulajdonú_gazdasági_társaságok","állami tulajdonú gazdasági társaságok","állami tulajdonú gazdasági társaságok"],
        [ "állami_vagyont_kezelő_szervek","állami vagyont kezelő szervek","állami vagyont kezelő szervek"],
        [ "egészségügy","egészségügy","egészségügy"],
        [ "közalapítvány","közalapítvány","közalapítvány"],
        [ "köztestület","köztestület","köztestület"],
        [ "kultúra_közgyűjtemény","kultúra, közgyűjtemény","kultúra, közgyűjtemény"],
        [ "oktatás","oktatás","oktatás"],
        [ "önkormányzati_fenntartású_közintézmény","önkormányzati fenntartású közintézmény","önkormányzati fenntartású közintézmény"],
        [ "önkormányzati_tulajdonú_gazdasági_társaságok","önkormányzati tulajdonú gazdasági társaságok","önkormányzati tulajdonú gazdasági társaságok"],
        [ "rendvédelem","rendvédelem","rendvédelem"],
        [ "szakmai_kamara","szakmai kamara","szakmai kamara"],
        [ "szociális-ellátás","szociális ellátás","szociális ellátás"]
])
