# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])

PublicBodyCategories.add(:hu, [ 
    "Közigazgatás",
        [ " minisztériumok","kormány, minisztériumok, kormányhivatalok","kormány, minisztériumok, kormányhivatalok"],
        [ "hatóságok"," hatóságok","hatóságok"],
        [ "felügyelőségek","felügyelőségek","felügyelőségek"],
        [ "rendvédelem","rendvédelem","rendvédelem"],
        [ "NMHH","médiahatóság","médiahatóság"],
        [ "versenyhivatal","versenyhivatal","versenyhivatal"],
        [ "PSZÁF","PSZÁF","PSZÁF"],
        [ "NAIH","Nemzeti Adatvédelmi és Információszabadság Hatóság","Nemzeti Adatvédelmi és Információszabadság Hatóság"],
    "Független állami szervek",
        [ "Országgyűlés","Országgyűlés"," Országgyűlés"],
        [ "Köztársasági_Elnök","Köztársasági Elnök","Köztársasági Elnök"],
        [ "Alkotmánybíróság","Alkotmánybíróság","Alkotmánybíróság"],
        [ "bíróság","bíróságok","bíróságok"],
        [ "ügyészségek","ügyészségek","ügyészségek"],
        [ "AJB","alapvető jogok biztosa","alapvető jogok biztosa"],
        [ "MNB","Magyar Nemzeti Bank","Magyar Nemzeti Bank"],
     "Közintézmények, közalapítványok",
        [ "egészségügy","egészségügyi intézmények","Egészségügyi intézmények"],
        [ "szociális","szociális intézmények","Szociális intézmények"],
        [ "oktatás","oktatási intézmények","oktatási intézmények"],
        [ "kultúra","kulturális intézmények, közgyűjtemények","kulturális intézmények, közgyűjtemények"],
        [ "közalapítványok","közalapítványok","közalapítványok"],
     "Önkormányzatok",
        [ "önkormányzatok","képviselőtestületek és polgármesteri hivatalok","képviselőtestületek és polgármesteri hivatalok"],
        [ "önkorm_közintézmények","önkormányzati fenntartású közintézmények","önkormányzati fenntartású közintézmények"],
     "Egyéb intézmények",
        [ "kamarák","szakmai kamarák","szakmai kamarák"],
        [ "MTA","Magyar Tudományos Akadémia","Magyar Tudományos Akadémia"],
        [ "MMA","Magyar Művészeti Akadémia","Magyar Művészeti Akadémia"],
        [ "állami_ gazdasági""állami tulajdonú gazdasági társaságok","állami tulajdonú gazdasági társaságok"],
        [ "önkormányzati _gazdasági","önkormányzati tulajdonú gazdasági társaságok","önkormányzati tulajdonú gazdasági társaságok"],
        [ "tulajdont_kezelő","állami-önkormányzati vagyont kezelő gazdálkodó szervezetek","állami-önkormányzati vagyont kezelő gazdálkodó szervezetek"],
        [ "egészségügyi_ellátók","társadalombiztosítással szerződött egészségügyi ellátók","társadalombiztosítással szerződött egészségügyi ellátók"],
        [ "egyéb","egyéb","egyéb"]
])
